"""create table sellers

Revision ID: ffbaf5869d9d
Revises: e66d64c1161c
Create Date: 2026-03-02 21:19:39.443721

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ffbaf5869d9d"
down_revision: Union[str, Sequence[str], None] = "e66d64c1161c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sellers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("birthday", sa.DateTime(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("rating", sa.Float(), server_default="0.0", nullable=False),
        sa.Column("orders_count", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sellers_email"), "sellers", ["email"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sellers_email"), table_name="sellers")
    op.drop_table("sellers")
    # ### end Alembic commands ###
